apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: ocp-4.4
  installPlanApproval: Automatic
  startingCSV: openshift-pipelines-operator.v1.0.1