apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../overlays/applications/jeagar-operator
  - ../../../overlays/applications/kiali-operator
  - ../../../overlays/applications/servicemesh-operator
#  - ../../../overlays/applications/elasticsearch-operator

resources:
  - service-mesh-init.yaml
