apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - git::https://github.com/redhat-canada-gitops/catalog/jaeger-operator/base/
  - ../../../overlays/applications/kiali-operator
  - ../../../overlays/applications/servicemesh-operator
  - ../../../overlays/applications/elasticsearch-operator
