apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-init
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/85matthew/application-catalog.git
    targetRevision: HEAD
    path: applications/service-mesh/overlays/default/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
