apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/applications/jaeger-operator/
  - git::https://github.com/redhat-canada-gitops/catalog/installplan-approver/base

patchesStrategicMerge:
  - patch-install-ns.yaml
