apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAHFVJlR4Tb8ZDRdgNeP21i6M0Gy6/mmdL46wuPde+6djpXLvUpvd4Hey7h7bsp2d9aTMJZ2MDLzeUjHGK2vGFy5krzhvi7GHK/GnGOoeoPzg4wvgvsKv0Ei1eh0TK+5ftfpnu25cM9wTEa411+vMA4kMLgcz0u/695kWHZ+AyHacDIWehH/G5ArP4W6T9t5P6FVz4PkwocxH/A/Kb9AXX8CHtEo2cUbQSXh5+k4/iOyUIf4anEQvkD9om/7km48gXNani4ykNHanEYxOtNELIf+4TA5pvW/slzERu+RXPz9eOaqaI/lZBh+1s9hFqmlMwIkl5m02fqG7+CRStHAg7cX8XeQqjlyBlj0nWbNcgqEZ1xo3i4Rfhw2ukuLjl7nXNePkzE7sryIixBfJsUM4W89FPPwQNx2BOGIm5C9FrFyO+/KCWLEo/M7YPyMLY3jr6/fCG1uTUQpE0jAtnXMmBQZjU+nbJimmbZg9DQWRCFWwKAzYISEo5HU4k9qObSajJ9BQo6SgFIhb5yD2U7nH2PJqpkHytUg2UoSOCnwGG+2OE6MfvICwnZSFTphOQHuyO8MzNyl8hBCdUwnhj3iMT+cVR/sQ9SpYJHx0te/dYb+IgfNJDGw91S2CO+9kZyPHqWtEOW0G+h5sFLicbu020u1lUgSi8mtmjhNKF7d0eK+Tx7dL2C+h2VrzqOEmuPsTIQvtO1Zzso3kTv6OBq8QNQmXjde5Hcb2pHbReoCwOSnSY4zWQUJv3Iwk81BWNgpib87QUVPBeSM6ucgDdKilo6QZJgWAoUklJ9aOHlQBUEKZG4KzcpOg09PoXYs52dK5eEn1TNLaGhdDKA7C9PsBYvA0l4ArBfTNb4LrdvHnE+OiaNyf9bKwStPzMtdmm7Sm1XrvGkHPWIpis5/DfSFZzMQMV7Kvd6iqteMzVfqDS2H1/JcHs6gYRqDyJBnHQIFb+6nugYhHMQf41lDA1VkNUOlOexC3TyBKtMq8q3pmR9lZ1hr+WBdr6jsfYXr3k6uNCSN/vi4y8jId4Jjv4ROk/K4y6FILGPZJcqpCvkTBGEk4TY1OiaB+0un8t+b4pKd4XCHu7rEZpGru88vbYZfhl4Dx6g6ov7KUY4OQoYxCeVByReOegx4i+/jKV7YyOQJ4jF0g//i/Szs5R0HttKjq0bkv5WhgqBRanqvCyk8zr3MJ/i8rjPxiKZMKvRp4M1/reSgxXVNquizAh1RQg99UHiZ6Ta+hcOGtPGDhRtILOF75n523IdpCmvshgaY1jcurriIoDONA79mmTZIRmsOAuZV6MJd5GqkBUFPrxYr/Zwcl8TZjGHj/8aVYtuFr3MV7fQvg==
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

