apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBoqHlWOLkLu0Q0N+M4z9owdhkQLy3cc9Lscv5SCuiDPTyrtH3Lh5k1HNVlOZo6PYAqR3buF+hVdLK2OYNQeohprgi9je7imCRVljB4LvqiOEwIEMm/Sms9kFwN+KUibc5+uIrzuFZnEWEM762rFkyS8zlciZ88MLA51dXwa2dBxxRhaLk8i4wReN9GMs4BnIStMrctLVgC7jlATj7Z9weptwNzklQRVbZCdKJFwxEQkF+t8BZ8EDql8hxKAZvXOCwPsidOvd2+Nockhh7M4l8dJwXvzXImdC+icJD5goTRm5Hl3O1MlSr9D4C36taKiU9JR0SNJ0ykYWAnPQOjll0AxZlbfv8RPWCKdiOPx3qSr/2JMFFoG9a772AZIRGw9/qmksPodNn8BEtNWvB3dvOpoZaik5eWnCaffvafsQGOyjKAeDkBXPgcjOhRGkpAt5IAmBT5ydCuwufeb/u0mkuq0fDUb/iofCJmgvj1Ix8gn8S44dBDlLz8awvS34OeM+HlPqv1PyqvTGzhKlGAAt37GfnoOKdSNlFVinj39fsavT7q2nLR/4MssjW2d55sjb8b8LlZyA1AF9oGd4ejFb330dTYiBaNlmr/uaOSdCgoYBvH/PSDp+B4ys8+n2dc3eBLIH5qD5APizZMJhgK4FTW8JOVwcflQgIY98ZZDLze/LaB1mUgPvSkGLtsi7C/7F11oLeBoGU5fHAKX8KN4SiypHsv6ahjvPFm/PxJGqrTyAhQiiBrkSdiq50XCNnyxwPV7505l/mA7NPu660K4DjLCppBChlKJfuJs9SdUsCCaWMKIQpZmyuH264HJ9b5AtDHYseSwdTj3pY+BvzXSaY5iE1MtwN+FSEljDO+R5i3KiMcq2draAtaIO3OCqbJTGwkgGRQ04qA4SCz0PKX9LpQzcAVm3nv30nnszkAPF4oTidjDM8ruB/hweijqePCX4nsQQAwa4yltkh2T8iFOmv7GdNHeg3PwH1K5VlILGhKcTaLGm21q6798hPyLVNexzMEPkw2UEMyw2v8lHkXyZq0BRnDGRdKYjx6kz++y5p7CoEZuc8AyFwLJQgufxmw/AtNy56E4fUSi0DMWpcXByP6oNbQ799fER+dKUg=
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

