apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgA5On+KGzbV7xReAAytL2+puDH0f5Xud8kRaX/AWQAG6CZd9rrTyuv/Q1zNhc+WkHAO8UidMhF7O4uy5/3MYF/cu0S2EQmrEc0ZaVpipubDO0NSRFHBCI2CV5XBva+taMe8vbaO9xiEO9qiIbVMRzeE9SWTwXvkolIuMaEV/tMxvzupZTr2PlbbW0vXGHsIG2mMS6yX9zvpPN8A5RPa7M3M2YKIWL5Oy++Ziv7GZQFAzkJN1vGOirYALRYf7OUwo/kxYEvocSRFZniYZgfElJn7fXVpnroraphak4QlA/A7TqJraI2nb+oC4hk5ZAUluwldT7gglb0rsnhoIzn9G9WUtW9x862OZDVKAd8Uh04y7AzP9krKtjn8a3oEc+Nu1/+NFIy/jyCi47R/Birk2PhC9MFeQO4X1dsi3pxsuR3Gon34Upvhd4UIe80+cn1U68OF8teElTDuyjDJ4Mi+2I6Y3d6uNdZPXJQvMvyrlYhMvIZTff9PS7WccJdc+nV1gyCc6fPPGFHJkzSEJGKUVH9E3/dfabgRguhTrWk6JfBsvsMOeV1iLKA0Ek2cI/C0FGvUOi0A0o4/aukf9Tv/Y4cN4AWio2l1GBMEG/E+LX0JXxwWlYlxTxgbnnDBII93aJmL9DbZOty3BcFxflcxq/yVwDYzPJ4I8j+jf0zbKgg0Wdl11pdGpAjNIkin7kaE79aH+DYM86DEeohU3I2ikm2fNxWMn7mQdaHa4LET5qgKkUiIr/I5ifm0kO8YnnNBBOKw66VzRKxI5wG8iCSJ4gTV6mDr8NOPHHgrsr6cts3NSmJLUvN1Xhyw6Id8YLy9VhBOW7+pEfiH66NZljE+CsE0GzNg2nZKqzBoL9Ski7e/5OtEb5IXMRA1LRer02ldbNEDuH/PiTQy2qagvsFTIBw518cL/jPt9PLbbn6DyGgqnL3weKs0kldC7QeUlewfwiXIkCyR0v1kTPlfhodAfUd+fWDVvW9NLpiVpq/1WSVlke2y3/cSmmh+ViWUFH50rAT56/gb5WRftolJO1GX7EW7YKvvBadYtEDu/rTpLRPPZ3EVD4SL5kvOwQDUdrma4GvM4URk/CtqHkqogKvw++QY+8netznN0sbrxlA=
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

