apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAD7QA1/MbmvhqfqKU/dmKlMqgdNQW/Yn3V6pMDdSexRwnTljUSANDaOP3hIhpl0VxHFBeqsWemoUEd9Bgj5AliHemFERyLjfZlosV7nTbP/3ixPamcUNOwMJaKGJ7XDHLXKw005NKFQc7F97AevCtSljZhhB8q+fQqzOFGerx3pvXQWKKBYCxrLhri416Iyq5VU6gOIV8lbOaR8q3FumUpFgFgPzmP08MdOBox7neD+DWReYOkZtngriCFEh7RSha18cGGTRfuoDD4EmGZVeR2g5sJgrGhwrVOidggoKEOsl+NllAMPzxcglIduAh2WtNW9eJ1JYA00ZZhrwYvHWH/iPi8MU8LgREe5g3mpjAFJdEvoBsl//7sOdnrUvF4Lf6aa/1AtqGFktFYimSAwRMC9gHB+6bDvGAgM/m0d/CNE/JrT1TssBl+VYchx18U2eYTE6FqMFkzTfs8ZR7Sp47r8c0r8xS1VdVg5b15y8K6rMrjVnzjLOV5ZVp9hRmIfoo9uqyN5NU4faxGHnbBtjNT1NAQtt69+JTk+q15B78QaVv+5qLEFV3glDrRoJjKx8KZSedP03+gDYRcSo+ieQnIz6xNCdXU3kF+02Sc/ILdxskJxS4hQPK1ox2wZVdv7v34WCM4un+XI7qR/PttdprlozkBVxDu6lQIAQZxPUf/tUPX6b6bRcfFnm8Wggq1kEOj/QWAVsD5cL2kiEWFB5eA/OrNlk4DrHPtJ79q/O15leLvGdiX0+VBFJiPnGta3KnJPPHwt/3eoj45kFcDc7DJDqXk0DcgSL4URHp6KUgby6SqpwfkYIoTlZse1A0xMBrITzGgGgYFGHNmqfWsyTqEDoJoeq6h6K9v8UBxf8pe46zoIhkubmzFPQ6g7rMK+x21/AaussiMxOArNu6v7hsAnkJzC4m533WRZP7byVSCU6AVOCTwdlKlkVNB0NVxk/tQGdAaIOSYCpiMJrufyqgKDc/Rq3Yk4WW5btNF7SZknGZEQfdr65cE8Kx9Fxf0Gb/7+rYodQ==
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config

